# Generated by Django 5.2.4 on 2025-07-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoSo',
            fields=[
                ('so_ho_so', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('bang_ke_dot_gan', models.CharField(max_length=20)),
                ('dot_nhap', models.IntegerField()),
                ('db_cu', models.CharField(blank=True, max_length=20, null=True)),
                ('hd_cu', models.CharField(blank=True, max_length=20, null=True)),
                ('db_moi', models.CharField(blank=True, max_length=20, null=True)),
                ('hd_moi', models.CharField(blank=True, max_length=20, null=True)),
                ('dot', models.IntegerField(null=True)),
                ('gb', models.IntegerField()),
                ('bu_dm', models.CharField()),
                ('hieu_luc', models.CharField(max_length=20, null=True)),
                ('ma_hd', models.CharField(blank=True, max_length=20, null=True)),
                ('ds_luu', models.CharField(blank=True, max_length=10, null=True)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('tro_ngai', models.CharField(blank=True, max_length=100, null=True)),
                ('quan', models.CharField(max_length=10)),
                ('lan_nhap', models.IntegerField(null=True)),
            ],
        ),
    ]
