# Generated by Django 5.2.4 on 2025-07-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoso',
            name='ds_luu',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
