# Generated by Django 5.2.4 on 2025-07-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_profiles', '0002_alter_hoso_ds_luu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoso',
            name='ds_luu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hoso',
            name='lan_nhap',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
