# Generated by Django 5.2.4 on 2025-08-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_profiles', '0003_alter_hoso_ds_luu_alter_hoso_lan_nhap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoso',
            name='tro_ngai',
            field=models.TextField(blank=True, null=True),
        ),
    ]
